# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import sys

sys.path.insert(0, "/Users/jsimp/Desktop/Keys")

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_file = '../output_data/clean_city_data.csv'
cities_df = pd.read_csv(weather_file)
cities_df

,City,Country,Latitude,Longitude,Temperature (F),Humidity (%),Wind Speed (mph),Cloudiness (%),Date
0,Katsuura,JP,35.13,140.30,57.99,71,3.00,4,1587236976
1,Punta Arenas,CL,-53.15,-70.92,55.40,43,17.22,57,1587236976
2,Albany,US,42.60,-73.97,44.01,66,1.99,98,1587236865
3,Ancud,CL,-41.87,-73.82,60.80,82,14.99,75,1587236976
4,Port Elizabeth,ZA,-33.92,25.57,68.00,94,9.17,3,1587236977
...,...,...,...,...,...,...,...,...,...
561,Boca do Acre,BR,-8.75,-67.40,89.17,34,5.03,26,1587237097
562,San Antonio,US,29.42,-98.49,62.01,72,8.05,90,1587236872
563,Pemangkat,ID,1.17,108.97,76.10,89,6.85,79,1587237098
564,Caucaia,BR,-3.74,-38.65,86.00,62,8.05,40,1587237098
565,Grants,US,35.15,-107.85,59.00,18,19.46,1,1587237098

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key = g_key)
locations = cities_df[['Latitude','Longitude']]
rating = cities_df['Humidity (%)']

In [4]:
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights = rating, dissipating = False, max_intensity = 300, point_radius = 5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
cold_cities = cities_df.loc[cities_df['Temperature (F)'] <= 70, :]
hot_cities = cities_df.loc[cities_df['Temperature (F)'] >= 80, :]
humid_cities = cities_df.loc[cities_df['Humidity (%)'] >= 75, :]
windy_cities = cities_df.loc[cities_df['Wind Speed (mph)'] >= 10, :]
cloudy_cities = cities_df.loc[cities_df['Cloudiness (%)'] >= 65, :]
sunny_cities = cities_df.loc[cities_df['Cloudiness (%)'] <= 25, :]
frames = [cold_cities, hot_cities, humid_cities, windy_cities, cloudy_cities, sunny_cities]

bad_cities = pd.concat(frames)

index = []
index.append(bad_cities.index.unique())

for index in index:
    nice_cities = cities_df.drop(index=index, inplace=False)

nice_cities.dropna()

,City,Country,Latitude,Longitude,Temperature (F),Humidity (%),Wind Speed (mph),Cloudiness (%),Date
68,Castro,BR,-24.79,-50.01,71.24,38,4.59,36,1587236989
133,Itabirito,BR,-20.25,-43.80,78.80,57,8.05,40,1587237003
218,Kutum,SD,14.20,24.67,77.40,11,9.66,62,1587237022
239,Chui,UY,-33.70,-53.46,70.14,70,6.78,32,1587237027
263,Santa VitÃ³ria do Palmar,BR,-33.52,-53.37,70.45,70,6.87,34,1587237032
307,Werda,BW,-25.27,23.28,78.76,22,2.77,42,1587237041
386,Enterprise,US,36.03,-115.24,71.01,32,3.36,40,1587237058
400,ValparaÃ­so,CL,-33.04,-71.63,71.60,53,5.82,28,1587236819
446,Bukama,CD,-9.20,25.85,73.26,73,1.72,62,1587237072

In [6]:
nice_cities['Humidity (%)'].count()

9

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
nice_cities["Hotel Name"] = ''
hotel_df = nice_cities[['City', 'Country', 'Latitude', 'Longitude', 'Hotel Name']]

In [8]:
params = {
    'key': g_key,
    'radius': 5000,
    'type': 'lodging',
    'keyword': 'hotel'
}

for index, row in hotel_df.iterrows():
    
    lat = row["Latitude"]
    lng = row["Longitude"]
    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response = requests.get(base_url, params=params).json()
    
    try:
        hotel_df.loc[index, 'Hotel Name'] = response['results'][0]['name']
        
    except (KeyError, IndexError):
        print('No hotel found in ' + row['City'] + '. Skipping...')
        
print('Done processing!')

C:\Users\jsimp\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

No hotel found in Kutum. Skipping...
No hotel found in Werda. Skipping...
No hotel found in Bukama. Skipping...
Done processing!

In [9]:
hotel_df = hotel_df.replace({'':'No hotel found'})
hotel_df

,City,Country,Latitude,Longitude,Hotel Name
68,Castro,BR,-24.79,-50.01,Hotel Buganville Express
133,Itabirito,BR,-20.25,-43.80,Cata White Green Village
218,Kutum,SD,14.20,24.67,No hotel found
239,Chui,UY,-33.70,-53.46,Bertelli ChuÃ­ Hotel
263,Santa VitÃ³ria do Palmar,BR,-33.52,-53.37,Mirante Hotel
307,Werda,BW,-25.27,23.28,No hotel found
386,Enterprise,US,36.03,-115.24,Hyatt Place Las Vegas At Silverton Village
400,ValparaÃ­so,CL,-33.04,-71.63,Hotel Palacio Astoreca
446,Bukama,CD,-9.20,25.85,No hotel found

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [11]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))